version: "3"

services:
  app:
    env_file:
      - .env
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_DB=app
    #   - POSTGRES_PASSWORD=app_password
    #   - POSTGRES_HOST=localhost
    #   - POSTGRES_PORT=5432
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3    
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres-data: